name: flutter_gastos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  rect_getter: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/undraw_Investment_data_re_sh9x.png
